# Pure Python vs. Numpy - Lab

## Introduction 

Numpy, Scipy and Pandas libraries provide a significant increase in computational efficiency with complex mathematical operations as compared to Python's built in arithmatic functions.  In this lab we shall calculate and compare the processing speed required for calculating a dot product both using basic arithmatic operations in Python and Numpy's `.dot()` method. 

## Objectives
You will be able to:
* Compare the performance of high dimensional matrix operations in Numpy vs. pure Python

## Problem
> **Write a routine to calculate the dot product between two 200 x 200 dimensional matrices using:**

> **a) Pure Python**

> **b) Numpy's `.dot()`**


### Create two 200 x 200 matrices in Python and fill them with random values using `np.random.rand()` 

In [1]:
# Compare 200x200 matrix-matrix multiplication speed
import numpy as np

def create_matrix (row, col):
    a = np.zeros ([row, col])
    for r in range(0,row):
        for c in range(0,col):
            a[r][c] = np.random.randint(0,10,1)
    return a

# Set up the variables
A = create_matrix(200,200)
B = create_matrix(200,200)
print( A)
print(B)

[[4. 3. 8. ... 0. 3. 3.]
 [7. 0. 3. ... 8. 3. 5.]
 [9. 0. 8. ... 1. 8. 9.]
 ...
 [5. 3. 4. ... 4. 1. 1.]
 [5. 1. 1. ... 0. 7. 6.]
 [2. 2. 2. ... 6. 0. 0.]]
[[7. 4. 2. ... 9. 9. 1.]
 [6. 4. 9. ... 2. 0. 4.]
 [0. 2. 7. ... 3. 1. 6.]
 ...
 [5. 2. 4. ... 1. 4. 0.]
 [6. 6. 7. ... 8. 6. 6.]
 [3. 3. 5. ... 6. 5. 6.]]


### Pure Python

* Initialize an zeros filled numpy matrix with necessary rows and columns for storing result. 
* In Python Calculate the dot product using the formula 
![](formula.png)
* Use Python's `timeit` library to calculate the processing time. 
* [Visit this link](https://www.pythoncentral.io/time-a-python-function/) for an indepth explanation on how to time a function or routine in python. 

**Hint**: Use nested for loop for accessing, calculating and storing each scalar value in the result matrix.

In [4]:
import timeit

# Start the timer
start = timeit.default_timer()


# Matrix multiplication in pure Python
C = np.zeros([A.shape[0],B.shape[1]])

for a_row in range(0,A.shape[0]):
    for b_col in range (0,B.shape[1]):
        num = 0
        for a_col in range (0,A.shape[1]):
            num+= A[a_row][a_col]*B[a_col][b_col]
        
        C[a_row][b_col] = num

time_spent = timeit.default_timer() - start

print('Pure Python Time:', time_spent, 'sec.')

Pure Python Time: 5.601030517297652 sec.


## Numpy 
Set the timer and calculate the time taken by `.dot()` function for multiplying A and B 


In [5]:
# start the timer
start = timeit.default_timer()

# Matrix multiplication in numpy
C = A.dot(B)


time_spent = timeit.default_timer() - start
print('Numpy Time:', time_spent, 'sec.')

Numpy Time: 0.01167226251950737 sec.


### Your comments 

```Numpy is exponentially faster in calculating the dot product that pure python language.
```

## Summary

In this lab, we performed a quick comparison between calculating a dot product in numpy vs python built in function. We saw that Numpy is computationally much more efficient that Python code due to highly sophisticated implementation of Numpy source code. You are encouraged to always perform such tests to fully appreciate the use of an additional library in Python. 